name: test workflow
on:
  push:
jobs:
  test-echo:
    runs-on: ubuntu-latest
    steps:
    - name: echo a failure
      run: exit 1
    - name: run this step even on failure
      if: failure()
      run: echo "i ran"
    - name: fail again
      run: exit 1
    - name: this will not trigger
      run: echo "hello-world"
