name: test workflow
on:
  push:
jobs:
  test-echo:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - name: echo a failure
      run: exit 1
      continue-on-error: true
    - name: run this step even on failure
      if: failure()
      run: echo "i ran"

    - name: step2
      if: failure()
      run: echo "ran after failure"
    - name: skipped-step 
      run: echo "did i skip"
    - name: fail again
      run: exit 1
    - name: this will not trigger
      run: echo "hello-world"

  job-2:
    runs-on: ubuntu-latest
    steps:
    - name: echo something
      run: echo "hello from job-2"
    
